name: My Express App Deploy
on:
  push:
    branches: ["main"]
        
  workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest        
        steps:
            - name: Downcase repo name
              run: |
                echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

            - name: Deploy latest image on EC2
              uses: appleboy/ssh-action@v0.1.0
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                  docker pull ghcr.io/${{ env.REPO_LOWER }}:latest
                  docker stop my-express-app || true
                  docker rm my-express-app || true
                  docker run -d --name my-express-app -p 80:3000 ghcr.io/${{ env.REPO_LOWER }}:latest
